peso=float(input('Introduce tu peso en kilogramos: '))
altura=float(input('Introduce tu altura en metros, con un punto: '))
imc=peso / (altura**2)
imcRedo=round(imc,2)
print ('Tu IMC es ' +str(imcRedo))
